// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmPZJj0IlvSgSVmYAIdXzFVMhCY8R80XU',
    appId: '1:968676266955:web:c2959ec37857f09e951c4e',
    messagingSenderId: '968676266955',
    projectId: 'e-study-management',
    authDomain: 'e-study-management.firebaseapp.com',
    storageBucket: 'e-study-management.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQuKYxP5uEGLAt5bucmzZuX8sFvnQtiA0',
    appId: '1:968676266955:android:bd60b034c584be2f951c4e',
    messagingSenderId: '968676266955',
    projectId: 'e-study-management',
    storageBucket: 'e-study-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfjmVVogoD_waxm5xuhV2byA-znyqOeZs',
    appId: '1:968676266955:ios:2a62df7d782d07b1951c4e',
    messagingSenderId: '968676266955',
    projectId: 'e-study-management',
    storageBucket: 'e-study-management.appspot.com',
    androidClientId: '968676266955-1cdkokf6srljqbpt9n1b3qe7l3cerro9.apps.googleusercontent.com',
    iosClientId: '968676266955-s6bbfkh9gbnq4293ub2p8ik6pbigb5cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStudyManagement',
  );
}
